[project]
name = "ComfyUI-CCXManager"
description = "专门为SD-PPP插件开发的辅助节点，自动管理和更新Photoshop侧插件"
version = "1.0.0"
authors = [
  { name = "WWWEN8"}
]
license = { file = "LICENSE" }
readme = "README.md"
homepage = "https://github.com/WWWEN8/ComfyUI-CCXManager"
repository = "https://github.com/WWWEN8/ComfyUI-CCXManager.git"

[tool.pytest.ini_options]
pythonpath = ["."]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"